name: Lint CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive 

    - name: Install verilator
      run: |
        sudo apt-get install -y verilator

    - name: Lint
      run: |
        make lint