name: Verify CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Verify
    runs-on: ubuntu-22.04
    container: verilator/verilator:v5.018
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive 

    - name: Install dependencies
      run: |
          apt-get update
          apt-get install -y cmake make g++ git

    - name: build fmt
      run: |
        cd 3rd-party/fmt && mkdir build && cd build && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE .. && make -j
    
    - name: verify
      run: |
        bash ./scripts/verify.sh